server:
  port: 8090
  servlet:
    context-path: /api/log-stream-poc

spring:
  application:
    name: log-stream-poc
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/log-stream-poc
      uuid-representation: standard
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: admin
      password: admin123
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: lz4
    consumer:
      group-id: log-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


security:
  jwt:
    secret: "xVWEhsxRgePf7i6W08Foilk9Ue3MNjna"
    expiration-time-ms: 3600000

springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs


logging:
  level:
    com.practice.log_stream_poc: INFO
    org.springdoc: DEBUG
    org.springframework.security: INFO