apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: external
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: internal
      port: 29092
      targetPort: 29092
      protocol: TCP
  selector:
    app: kafka