apiVersion: v1
kind: Service
metadata:
  name: log-stream-poc-service
  namespace: dev-log-stream-poc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: log-stream-poc-service