apiVersion: v1
kind: ConfigMap
metadata:
  name: log-stream-poc-config
  namespace: dev-log-stream-poc
data:
  application.yml: |-
    server:
      port: 8080
      servlet:
        context-path: /api/log-stream-poc
    
    spring:
      application:
        name: log-stream-poc
      data:
        mongodb:
          uri: mongodb://root:password@mongo:27017/log-stream-poc
          uuid-representation: standard
          auto-index-creation: true
      kafka:
        bootstrap-servers: kafka:29092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          compression-type: lz4
        consumer:
          group-id: log-consumer-group
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          fetch-min-size: 1000000
          fetch-max-wait: 3000
          max-poll-records: 1000
          enable-auto-commit: false
          properties:
            max.poll.interval.ms: 300000

  application-dev.yml: |-
    spring:
      profiles:
        active: dev