apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: dev-log-stream-poc
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
    - port: 29092
      targetPort: 29092
      protocol: TCP
  