apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: dev-log-stream-poc
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  selector:
    app: zookeeper